@startuml
'https://plantuml.com/class-diagram

IDistributionService <|-- DistributionService
IWslService <|-- WslService
DistributionService o-- Distribution
DistributionService --> IWslService


class Distribution
{
    + <<property>> Id: Guid
    + <<property>> Path: string
    + <<property>> IsDefault: bool
    + <<property>> WslVersion: int
    + <<property>> Name: string
    + <<property>> MemoryLimit: double
    + <<property>> ProcessorLimit: int     
}

interface IDistributionService
{
	+ InitDistributionsList(): void
    + GetAllDistributions(): IEnumerable<Distribution>
    + GetDistribution(id: int): Distribution
    + AddDistribution(distro: Distribution): void
    + DeleteDistribution(id: int): void
    + UpdateDistribution(distro: Distribution): void
}

class DistributionService
{
	- _distros: IList<Distribution>
	- _wslApi: WslApi
	- _wslService: IWslService
	+ InitDistributionsList(): void
	+ GetAllDistributions(): IEnumerable<Distribution>
	+ GetDistribution(id: int): Distribution
	+ AddDistribution(distro: Distribution): void
	+ DeleteDistribution(id: int): void
	+ UpdateDistribution(distro: Distribution): void
}

interface IWslService
{
	+ CheckWsl(): bool
}

class WslService
{
	- _wslApi: WslApi
	+ CheckWsl(): bool
}

class ProcessBuilderHelper
{
    - _process: Process
    + SetFileName(fileName: string): ProcessBuilderHelper
    + SetArguments(args: string): ProcessBuilderHelper
    + SetRedirectStandardOutput(val: bool): ProcessBuilderHelper
    + SetRedirectStandardError(val: bool): ProcessBuilderHelper
    + SetUseShellExecute(val: bool): ProcessBuilderHelper
    + SetCreateNoWindow(val: bool): ProcessBuilderHelper
    + Build(): Process
}

@enduml