name: Workflow for WSLStudio

on:
  push:
    branches: [ "master", "develop", "release/**" ]
  pull_request:
    branches: [ "master", "develop", "release/**" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    runs-on: windows-latest

    # TODO: Update environment variables.
    env:
      Solution_Name: WSLStudio.sln
      Project_Name: WSLStudio
      Test_Project_Name: WSLStudio.Tests.MSTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Restore
      run: dotnet restore $env:Solution_Name
  
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    #- name: Test
    #  run: dotnet test $env:Test_Project_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
