name: Workflow for WSLStudio

on:
  push:
    branches: [ "master", "develop", "release/**" ]
  pull_request:
    branches: [ "master", "develop", "release/**" ]

jobs:
  build:
    strategy:
      matrix:
          configuration: [Release]
          platform: [x64]

    runs-on: windows-latest

    # TODO: Update environment variables.
    env:
      Solution_Name: WSLStudio.sln
      Project_Name: WSLStudio
      Test_Project_Name: WSLStudio.Tests.MSTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore
      run: dotnet restore $env:Solution_Name
  
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
